pipeline {
    agent {
        docker { image 'mcr.microsoft.com/playwright:v1.47.2-jammy' }
    }
    environment {
        REPO_NAME = 'Tongram'
        FILE_SH = 'TG_Auto.sh'
        FILE_BAT = 'TG_Auto.bat'
        SERVER_PATH = "Automation-testing/${REPO_NAME}"
        SERVER_PROJECT = "Automation-testing"
        BRANCH_NAME = 'main'
        JENKINS_CREDENTIALS_ID = '5c7bd325-a531-4236-8534-102e45de69e7'
        chatId = '-1002308985537'
        botToken = '8085219018:AAHSTNao6k9OucZc15LQ476N-039N8NR7WI'
        RESULTS_FILE = "${env.REPO_PATH}/Results/test_results.json" 
    }
    triggers {
        cron('0 1 * * *')
    }

    stages {
        stage('CI: Checkout Code') {
            steps {
                script {
                    // Lấy thông tin mới nhất từ kho lưu trữ từ xa
                    sh "git fetch origin ${BRANCH_NAME}"
                    
                    // Kiểm tra sự thay đổi giữa nhánh local và nhánh remote
                    def changes = sh(script: "git diff --name-only origin/${BRANCH_NAME} ${BRANCH_NAME} || echo 'Error occurred in git diff'", returnStdout: true).trim()



                    if (changes) {
                        echo "Có thay đổi. Tiến hành checkout mã nguồn..."
                        withCredentials([usernamePassword(credentialsId: "${JENKINS_CREDENTIALS_ID}", usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')]) {
                            git branch: "${BRANCH_NAME}",
                                credentialsId: "${JENKINS_CREDENTIALS_ID}",
                                url: "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/DuyThanhLieu/Automation-testing.git"
                        }
                        echo "Mã nguồn đã được checkout từ nhánh ${BRANCH_NAME}"
                    } else {
                        echo "Không có thay đổi. Bỏ qua bước checkout."
                    }

                    // Tìm và gán đường dẫn kho lưu trữ vào biến REPO_PATH
                    env.REPO_PATH = sh(script: "find . -type d -name '${REPO_NAME}'", returnStdout: true).trim()
                    if (env.REPO_PATH) {
                        echo "Đã tìm thấy ${REPO_NAME} tại: ${env.REPO_PATH}"
                    } else {
                        error "Không tìm thấy thư mục kho lưu trữ ${REPO_NAME}."
                    }
                }
                sh """
                    cd ${env.REPO_PATH}
                    pwd
                    ls -la
                """
            }
        }

        stage('Setup Dependencies') {
            steps {
                echo 'Setting up dependencies'
                script {
                    sh """
                        cd ${env.REPO_PATH}

                        if [ -d "node_modules" ]; then
                            echo "node_modules already exists. Checking Playwright version..."
                            chmod +x node_modules/.bin/playwright

                            if npx playwright --version; then
                                echo "Playwright is already installed. Skipping installation."
                            else
                                echo "Playwright is not installed. Installing..."
                                rm -rf node_modules package-lock.json
                                npm install
                                npx playwright install
                                npm install @playwright/test@latest
                            fi
                        else
                            echo "node_modules does not exist. Installing dependencies..."
                            npm install
                            npx playwright install
                            npm install @playwright/test@latest
                        fi
                    """
                }
            }
        }

        stage('CD: Run Tests') {
            steps {
                echo 'Starting Tests'
                script {
                    if (isUnix()) {
                        sh """
                            cd ${env.REPO_PATH}
                            chmod +x ${FILE_SH}
                            ./${FILE_SH}
                        """
                    } else {
                        bat """
                            cd ${env.REPO_PATH}
                            ${FILE_BAT}
                        """
                    }
                }
                echo "Tests executed"
            }
        }

        stage('Archive Test Results') {
            steps {
                archiveArtifacts artifacts: '**/playwright-report/**/*', allowEmptyArchive: true
                echo 'Test results archived.'
            }
        }
    }

    post {
        success {
            script {
                sendBuildStatusMessage("✅ Status: ${currentBuild.currentResult}")
                cleanTemporaryFolder()
            }
        }

        failure {
            script {
                sendBuildStatusMessage("❌ Status: ${currentBuild.currentResult}")
                cleanTemporaryFolder()
            }
        }
    }
}

def cleanTemporaryFolder() {
    script {
        echo 'Cleaning up temporary files and directories...'
        def pathsToCheck = [
            "${env.REPO_PATH}/package-lock.json",
            "${env.REPO_PATH}/playwright-report",
            "${env.REPO_PATH}/Results",
            "${env.REPO_PATH}/test-results",
            "${env.REPO_PATH}/temp",
            "${env.REPO_PATH}/logs"
        ]
        if (isUnix()) {
            pathsToCheck.each { path -> 
                sh "rm -rf ${path} || true"
            }
        } else {
            pathsToCheck.each { path -> 
                def winPath = path.replace("/", "\\")
                bat "del /Q ${winPath} || echo 'File not found'"
            }
        }
    }
}

def sendBuildStatusMessage(statusBuild) {
    TimeZone timeZone = TimeZone.getTimeZone('GMT+7')
    def currentDate = new Date().format("dd-MM-yyyy", timeZone)
    def currentTime = new Date().format("HH:mm:ss", timeZone)
    def durationMillis = currentBuild.duration ?: 0
    def minutes = (durationMillis / 60000).toInteger()  
    def seconds = ((durationMillis % 60000) / 1000).toInteger()  

    def commitId = env.GIT_COMMIT ?: 'N/A'
    def branchName = env.GIT_BRANCH ?: 'N/A'
    
    def message = """
    🌟🌟 ${statusBuild} 🌟🌟
    ══════════════════════ 
    📁 Repository: ${env.REPO_NAME}           
    📅 Date: ${currentDate} 
    🕒 Time: ${currentTime}                                  
    ⏳ Duration: ${minutes} min ${seconds} sec  
    ══════════════════════
    🌿 Branch: ${branchName}       
    🏷️ Commit ID: ${commitId}       
    🔗 Jenkins Server: ${env.BUILD_URL}       
    ══════════════════════
    🔗 Thank you for your attention! 🚀
    """
    
    sendMessageToTelegram(message)
}

def sendMessageToTelegram(message) {
    sh "curl -s -X POST https://api.telegram.org/bot${botToken}/sendMessage -d chat_id=${chatId} -d text='${message}'"
}
